language: python
python:
  - "3.5"
  - "3.6"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
# commands to run tests, generate coverage report, and pipe the report to coveralls:
# see https://levibostian.com/blog/python-code-coverage-and-coveralls-io/
script:
  - nosetests --with-coverage # run nose with coverage support.
after_success:
  - coveralls
